{{- range $name, $svc := .Values.services }}
{{- $ctx := dict "name" $name "root" $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "k8coins.labels" $ | nindent 4 }}
    {{- include "k8coins.selectorLabels" $ctx | nindent 4 }}
spec:
  {{- if not $svc.autoscaling.enabled }}
  replicas: {{ $svc.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8coins.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8coins.selectorLabels" $ctx | nindent 8 }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $.Values.image.registry }}/k8coins-{{ $name }}:{{ include "k8coins.tag" $ }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: k8coins-config
          ports:
            - name: http
              containerPort: {{ $svc.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "k8coins.labels" $ | nindent 4 }}
    {{- include "k8coins.selectorLabels" $ctx | nindent 4 }}
spec:
  selector:
    {{- include "k8coins.selectorLabels" $ctx | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- if $svc.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  labels:
    {{- include "k8coins.labels" $ | nindent 4 }}
    {{- include "k8coins.selectorLabels" $ctx | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $svc.autoscaling.minReplicas }}
  maxReplicas: {{ $svc.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $svc.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
---
{{- end }}
